forum/urls.py
from django.contrib import admin
from django.urls import path
from .views import BranchDetailView, BranchListView, PostDetailView, CommentaryCreateView, \
    PostCreateView, PostDeleteView, CommentDeleteView, GradeCreateView, get_rating_view, PostListView, \
    index, set_dark_theme, set_light_theme

urlpatterns = [
    path('', index, name='index'),
    path('posts/', PostListView.as_view(), name='post-list'),
    path('branches/', BranchListView.as_view(), name='branch-list'),
    path('branch/<int:pk>/', BranchDetailView.as_view(), name='branch-detail'),
    path('branch/<int:pk>/post-create/', PostCreateView.as_view(), name='post-create'),
    path('branch/<int:bk>/post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('branch/<int:bk>/post/<int:pk>/delete', PostDeleteView.as_view(), name='post-delete'),
    path('branch/<int:bk>/post/<int:pk>/comment/<int:cr>/delete', CommentDeleteView.as_view(), name='comment-delete'),
    path('branch/<int:bk>/post/<int:pk>/comment/<int:cr>/create', CommentaryCreateView.as_view(), name='comment-create'),
    path('rating/', GradeCreateView.as_view(), name='rating'),
    path('get-rating/', get_rating_view, name='rating'),
    path('set-light-theme/', set_light_theme, name='set-light-theme'),
    path('set-dark-theme/', set_dark_theme, name='set-dark-theme'),
]

reddit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('auth_sys.urls')),
    path('', include('forum.urls')),
    path('', include('user_profile.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

# Create your models here.

class Rating(models.Model):
    sum_rating = models.IntegerField(default=0)

    def get_rating(self):
        return sum([grade.value for grade in self.grades.all()])

class Grade(models.Model):
    rating = models.ForeignKey(to=Rating, on_delete=models.CASCADE, related_name='grades')
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True, related_name='grades')
    value = models.IntegerField(choices=[(1, 'Like'), (-1, 'Dislike')])
    time_create = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('rating', 'user')
        ordering = ('-time_create',)
        indexes = [models.Index(fields=['-time_create', 'value'])]
        verbose_name = 'Grade'
        verbose_name_plural = 'Grades'
    
    def __str__(self):
        return f'{self.user.username} {self.value}'

class Branch(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField()

    def get_absolute_url(self):
        return reverse('branch-detail', kwargs={'pk': self.pk})

    def __str__(self) -> str:
        return f'{self.name}'

    class Meta:
        verbose_name = "Branch"
        verbose_name_plural = "Branches"


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='posts')
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE, related_name='posts')
    title = models.CharField(max_length=255)
    description = models.TextField()
    created = models.DateTimeField(auto_now=True)
    rating = models.OneToOneField(Rating, on_delete=models.CASCADE, related_name='post', blank=True, null=True)

    def delete(self, *args, **kwargs):
        if self.rating:
            self.rating.delete()
        super(Post, self).delete(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk,
                                              'bk': self.branch.pk})

    def __str__(self) -> str:
        return f'{self.title}'

    class Meta:
        verbose_name = "Post"
        verbose_name_plural = "Posts"

class Commentary(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    commentary = models.ForeignKey('Commentary', on_delete=models.CASCADE, related_name='comments', blank=True, null=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='comments')
    text = models.TextField()
    created = models.DateTimeField(auto_now=True)
    rating = models.OneToOneField(Rating, on_delete=models.CASCADE, related_name='comment', blank=True, null=True)

    def delete(self, *args, **kwargs):
        if self.rating:
            self.rating.delete()
        super(Commentary, self).delete(*args, **kwargs)

    def __str__(self) -> str:
        return f'{self.text}'
    
    class Meta:
        ordering=['-created']
        verbose_name = "Comment"
        verbose_name_plural = "Comments"

forum/forms.py
from django import forms
from .models import Commentary, Post


class CommentaryCreationForm(forms.ModelForm):
    class Meta:
        model = Commentary
        fields = ['text']

    def __init__(self, *args, **kwargs):
        super(CommentaryCreationForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control', 'rows': 1})


class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'description']

    def __init__(self, *args, **kwargs):
        super(PostCreateForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control', 'rows': 1})

forum/views.py
from typing import Any
from django.shortcuts import render, get_object_or_404, redirect, HttpResponseRedirect, resolve_url
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.db.models import Sum

from django.views.generic import ListView, DetailView, View, CreateView, TemplateView
from .forms import CommentaryCreationForm, PostCreateForm
from .models import Branch, Post, Commentary, Rating, Grade
from django.db.models import Sum
from .mixins import HavePermissionsMixin

# Create your views here.

def index(request):
    return HttpResponseRedirect(resolve_url('post-list'))

class BranchListView(ListView):
    model = Branch
    template_name = "forum/branch-list.html"
    context_object_name = 'branches'

class BranchDetailView(DetailView):
    model = Branch
    template_name = "forum/branch-detail.html"
    context_object_name = 'branch'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        _posts = self.get_object().posts.all()
        if self.request.GET.get('order_by') is None:
            _posts = _posts.order_by('-rating__sum_rating')
        else:
            _posts = _posts.order_by('-created')
        context['posts'] = _posts

        return context

class PostListView(ListView):
    model = Post
    template_name = "forum/post-list.html"
    context_object_name = 'posts'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        _posts = self.model.objects
        if self.request.GET.get('order_by') is None:
            _posts = self.model.objects.order_by('-rating__sum_rating')
        else:
            _posts = _posts.order_by('-created')
        context['posts'] = _posts

        return context

class PostDetailView(DetailView):
    model = Post
    template_name = "forum/post-detail.html"
    context_object_name = 'post'        
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentaryCreationForm()
        post = self.get_object()

        _comments = Commentary.objects.filter(post=post, commentary__isnull=True)
        if self.request.GET.get('order_by') is None:
            _comments = _comments.order_by('-rating__sum_rating')
        else:
            _comments = _comments.order_by('-created')
        context['comments'] = _comments

        return context
    
class CommentDeleteView(HavePermissionsMixin, View):
    model = Commentary

    def get_object(self):
        return get_object_or_404(self.model, pk=self.kwargs.get('cr'))

    def post(self, request, *args, **kwargs):
        commentary = self.get_object()
        commentary.delete()

        return HttpResponseRedirect(commentary.post.get_absolute_url())

class CommentaryCreateView(LoginRequiredMixin, View):
    form_class = CommentaryCreationForm
    model = Commentary

    def get_post(self, **kwargs):
        post_id = self.kwargs.get('pk')
        return get_object_or_404(Post, pk=post_id)
    
    def get_comment(self, **kwargs):
        comment_id = self.kwargs.get('cr')
        return get_object_or_404(Commentary, pk=comment_id)
    
    def post(self, request, *args, **kwargs):
        comment_form = CommentaryCreationForm(request.POST, request.FILES)

        if comment_form.is_valid():
            comment = comment_form.save(commit=False)

            comment.author = request.user
            comment.post = self.get_post()
            if self.kwargs.get('cr'):
                comment.commentary = self.get_comment()
            comment.save()
            rating = Rating.objects.create()
            comment.rating = rating
            comment.save()
            return HttpResponseRedirect(comment.post.get_absolute_url())
        return render(request, "forum/comment-create.html", {'form': comment_form})
    
class PostDeleteView(LoginRequiredMixin, HavePermissionsMixin, View):
    model = Post

    def get_object(self):
        return get_object_or_404(self.model, pk=self.kwargs.get('pk'))

    def post(self, request, *args, **kwargs):
        post_object = self.get_object()
        post_object.delete()

        return HttpResponseRedirect(post_object.branch.get_absolute_url())

class PostCreateView(LoginRequiredMixin, TemplateView):
    template_name = "forum/post-create.html"
    form_class = PostCreateForm
    model = Post

    def get_branch(self):
        return get_object_or_404(Branch, pk=self.kwargs.get('pk'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = PostCreateForm()
        return context

    def post(self, request, *args, **kwargs):
        post_form = PostCreateForm(request.POST, request.FILES)
        if post_form.is_valid():
            post_object = post_form.save(commit=False)

            post_object.author = request.user
            post_object.branch = self.get_branch()
            post_object.save()
            rating = Rating.objects.create()
            post_object.rating = rating
            post_object.save()
            return HttpResponseRedirect(post_object.get_absolute_url())
        return render(request, self.template_name, {'form': post_form})


class GradeCreateView(LoginRequiredMixin, View):
    model = Grade
    
    def post(self, request, *args, **kwargs):
        rating = Rating.objects.get(pk=request.POST.get('rating'))
        value = int(request.POST.get('value'))
        user = request.user if request.user.is_authenticated else None
        grade, created = self.model.objects.get_or_create(
            rating=rating,
            user = user,
            defaults={'value': value},
        )
        response = JsonResponse({'status': 'created', 'rating_sum': grade.rating.get_rating(), 'grade': grade.value})
        if not created:
            if grade.value == value:
                grade.delete()
                response = JsonResponse({'status': 'deleted', 'rating_sum': grade.rating.get_rating(), 'grade': 0})
            else:
                grade.value = value
                grade.user = user
                grade.save()
                response = JsonResponse({'status': 'updated', 'rating_sum': grade.rating.get_rating(), 'grade': grade.value})
    
        rating.sum_rating = rating.get_rating()
        rating.save()
        return response
    
def get_rating_view(request):
    if request.user.is_authenticated:
        rating = Rating.objects.get(pk=request.GET.get('rating'))
        grade = rating.grades.all().filter(user=request.user).last()
        if grade:
            return JsonResponse({'grade': grade.value})
    return JsonResponse({'grade': 0})

def set_dark_theme(request):
    request.session['theme'] = 'dark'

    previous_url = request.META.get('HTTP_REFERER')
    if previous_url:
        return HttpResponseRedirect(previous_url)
    return HttpResponseRedirect('/')

def set_light_theme(request):
    request.session['theme'] = 'light'

    previous_url = request.META.get('HTTP_REFERER')
    if previous_url:
        return HttpResponseRedirect(previous_url)
    return HttpResponseRedirect('/')

templates/forum/branch-detail.html
{% extends 'base.html' %}

{% block content %}


<div class="row">
    <div class="col">
        <h2>{{ branch.name }}</h2>
        <p>{{ branch.description }}</p>
    </div>
    <div class="col">
        <a style="float: right;" class="btn btn-danger m-2" href="{% url 'post-create' branch.pk %}">Create post</a>
    </div>
</div>
<hr>
<h4>Order by</h4>
<a href="{% url 'branch-detail' branch.id %}?order_by=new" class="btn btn-outline-secondary me-2">New</a>
<a href="{% url 'branch-detail' branch.id %}" class="btn btn-outline-secondary me-2">Popular</a>
{% for post in posts %}
    {% include 'forum/objects/post.html' with post=post %}
{% endfor %}

{% endblock content %}

templates/forum/branch-list.html
{% extends 'base.html' %}

{% block content %}


{% for branch in branches %}
    <div class="container border mt-2 mb-3 pt-1" style="border-width: 2px; border-radius: 20px">
        <div class="card" style="border: none; background-color: transparent">
            <p class="bold-text m-0">{{ branch.name }}</p>
            <p class="mb-1">{{ branch.description }}</p>
            <a href="{{ branch.get_absolute_url }}" class="stretched-link"></a>
        </div>
        <div class="d-flex">
            <p><i class="fa fa-file" aria-hidden="true"></i> {{ branch.posts.all|length }}</p>
        </div>
    </div>
{% endfor %}

{% endblock content %}

templates/forum/comment-create.html
{% extends 'base.html' %}

{% block content %}

<h2>Create a comment</h2>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-danger" value="Save">
</form>

{% endblock content %}

templates/forum/comment.html
<li>
    <div>
        <div class="d-flex">
            <div style="align-items: flex-end; flex-direction: row; background-color: transparent; border: none;" class="card d-flex">
                <img style="border-radius: 50%;" src="{{ comment.author.profile.image.url }}" width="38" height="38" class="d-inline-block align-text-top">
                <small style="font-weight: 500;" class="m-1">{{ comment.author.username }}</small>
                <small style="color: gray;" class="m-1">{{ comment.created }}</small>
                <a class="stretched-link" href="{% url 'profile' comment.author.profile.pk %}"></a>
            </div>
        </div>
        <p style="margin-left: 40px; " class="mb-0">{{ comment.text }}</p>
    </div>
    <div {% if not comment.comments.exists %}style="margin-left: 32px;"{% endif %} class="d-flex">
        {% if comment.comments.exists %}
            <a class="nav-link dropdown-toggle me-2" style="font-weight: 1000;" data-bs-toggle="collapse" href="#CollapseComment{{ comment.pk }}" role="button" aria-expanded="false" aria-controls="CollapseComment{{ comment.pk }}">+</a>
        {% endif %}
        <div style="align-items: flex-start" class="rating-buttons comment d-flex" data-comment="{{ comment.id }}">
            <button class="btn btn-sm btn-outline-dark" style="border: none; border-radius:40%" data-rating="{{ comment.rating.id }}" data-value="1">
                <i class="fa fa-thumbs-up fs-5 far" data-rating="{{ comment.rating.id }}" data-value="1"></i>
            </button>
            <p class="rating-sum">{{ comment.rating.get_rating }}</p>
            <button class="btn btn-sm btn-outline-dark" style="border: none; border-radius:40%" data-rating="{{ comment.rating.id }}" data-value="-1">
                <i class="fa fa-thumbs-down fs-5 far" data-rating="{{ comment.rating.id }}" data-value="-1"></i>
            </button>
        </div>
        <a class="nav-link dropdown-toggle" style="font-weight: 600;" data-bs-toggle="collapse" href="#CollapseReply{{ comment.pk }}" role="button" aria-expanded="false" aria-controls="CollapseReply{{ comment.pk }}">Reply</a>
        <form action="{% url 'comment-delete' post.branch.pk post.pk comment.pk %}" method="post">{% csrf_token %}
            <button type="submit" style="font-weight: 600;" class="nav-link ms-2">Delete</button>
        </form>
    </div>
    <div class="collapse multi-collapse" id="CollapseReply{{ comment.pk }}">
        <form action="{% url 'comment-create' post.branch.pk post.pk comment.pk %}" style="border: none;" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div id="text_area_div"></div>
            <div class="text-area-div">
                <textarea class="text-area" name="text" rows="1" id="id_text" placeholder="Add a comment" onkeyup="textarea_resize(event, 15, 2);"></textarea>
                <button type="submit" style="vertical-align: top; float: right" class="btn btn-danger m-2">Comment</button>
            </div>
        </form>
    </div>
    {% if comment.comments.exists %}
        <div class="collapse multi-collapse" id="CollapseComment{{ comment.pk }}">
            <ul>
                {% for reply in comment.comments.all %}
                    <div class="container mt-2">
                        {% include 'forum/comment.html' with comment=reply %}
                    </div>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
</li>

templates/forum/post-create.html
{% extends 'base.html' %}

{% block content %}

<h2>Create a post</h2>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-danger" value="Save">
</form>

{% endblock content %}

templates/forum/post-detail.html
{% extends 'base.html' %}

{% block content %}


<div class="mb-0 row">
    <div class="col-10">
        <small>Posted by <a href="{% url 'profile' post.author.profile.pk %}">{{ post.author.username }}</a></small>
        <small><a href="{{ post.branch.get_absolute_url }}">{{ post.branch.name }}</a></small>
        <small style="color: gray;" class="m-1">{{ post.created }}</small>
        <p class="m-0 mb-1 bold-text">{{ post.title }}</p>
        <p class="mb-1">{{ post.description }}</p>
    </div>
    <div class="col d-flex">
        {% if request.user.is_authenticated %}
        {% if request.user == post.author or request.user.is_moderator %}
        <form action="{% url 'post-delete' post.branch.pk post.pk %}" method="post" class="m-2 ms-auto">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="Delete">
        </form>
        {% endif %}
        {% endif %}
    </div>
</div>


<div class="d-flex">
    {% include 'forum/objects/rating-buttons.html' with object=post %}
    <p><i class="fa fa-comments" aria-hidden="true"></i> {{ post.comments.all|length }}</p>
</div>

<form action="{% url 'comment-create' post.branch.pk post.pk 0 %}" method="post" style="text-align: center;" class="mb-2" enctype="multipart/form-data">
    {% csrf_token %}
    <div id="text_area_div"></div>
    
    <div class="text-area-div">
        <textarea class="text-area" name="text" rows="1" id="id_text" placeholder="Add a comment" onkeyup="textarea_resize(event, 15, 2);"></textarea>
        <button type="submit" style="vertical-align: top; float: right" class="btn btn-danger m-2">Comment</button>
    </div>
</form>

<div class="mt-1">
    {% if comments.exists %}
        <h4>Order by</h4>
        <a href="{{ post.get_absolute_url }}?order_by=new" class="btn btn-outline-secondary me-2">New</a>
        <a href="{{ post.get_absolute_url }}" class="btn btn-outline-secondary me-2">Popular</a>
        <div class="p-0 mt-2">
            {% for comment in comments %}
                {% include 'forum/objects/comment.html' with comment=comment collapse_comments=True %}
            {% endfor %}
        </div>
    {% else %}
        <p>There are no comments here yet. You can make the first one!</p>
    {% endif %}
</div>
       


{% endblock content %}

templates/forum/post-list.html
{% extends 'base.html' %}

{% block content %}

<h3>Order by</h3>
<a href="{% url 'post-list' %}?order_by=new" class="btn btn-outline-secondary me-2">New</a>
<a href="{% url 'post-list' %}" class="btn btn-outline-secondary me-2">Popular</a>

{% for post in posts %}
    {% include 'forum/objects/post.html' with post=post %}
{% endfor %}

{% endblock content %}